# SPDX-License-Identifier: BSD-3-Clause
[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "opends"
version = "0.2.0"
description = "Python bindings for the OpenDS accelerator direct storage API"
requires-python = ">=3.8"
readme = "README.md"
license = { text = "BSD-3-Clause" }

[project.optional-dependencies]
test = ["pytest"]

[tool.setuptools.packages.find]
include = ["opends*"]
